DROP TABLE IF EXISTS employees;
CREATE TABLE employees (
      id  int(11) NOT NULL  auto_increment PRIMARY KEY,
      first_name VARCHAR(56),
      last_name VARCHAR(56)
  );

DROP TABLE IF EXISTS clientes;
CREATE TABLE clientes (
	ID INT NOT NULL AUTO_INCREMENT,
	NOMBRE VARCHAR(100) NOT NULL,
	APELLIDO VARCHAR(100) NOT NULL,
	CORREO VARCHAR(100) NOT NULL,
	DIRECCION VARCHAR(100) NOT NULL,
	TELEFONO VARCHAR(100) NOT NULL,
	PRIMARY KEY (ID)
	);

